### ISSUE TITLE
Hint in step 4

### ISSUE THREAD

**Issue by jennirpf** [raspberrypilearning/astronaut-reaction-times#17]
Hi!
In Step 4, the hint about the two blocks to use reads as follows:

> say [Hello!]
> 
> pick random (1) to (10)
> 
> wait (1) seconds

Should the first block be included? If so, should it read "say [Press the Space key when I say GO!]" for consistency with the rest of the code and where the blocks will be used?

Sorry if I have misunderstood!
Thanks, Jenni

**Comment by MarcScott** [comment]
Fixed - thank you @jennyrpf
