### ISSUE TITLE
"More images" link doesn't work on raspberrypi.org

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/astronaut-reaction-times#3]
When viewing https://www.raspberrypi.org/learning/astronaut-reaction-times/worksheet/ the link in "You can also find more images to use here if you do not like those." doesn't work correctly, it just goes to https://www.raspberrypi.org/learning/404.htm

**Comment by LornaLynch** [comment]
This should be fixed now, though it will take a little time for the update to show on the website.
